name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: build
      run: |
        ./release.sh

    - name: upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v1.0.0-alpha"
        prerelease: true
        title: "Alpha build"
        files: |
         
          g2fm-en_US.7z
          g2fm_multiarch.iso
          g2fmia32.efi
          g2fmx64.efi
          g2fm_multiarch.iso
          grubfm.elf
          grubfm.iso
          grubfmaa64.efi
          grubfm_pc.iso
          samples.7z
