name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: initialize
      run: |
        sudo -E apt-get -y install gettext grub2-common genisoimage p7zip-full mtools xorriso

    - name: update grub2
      run: ./update_grub2.sh

    - name: build
      run: |
        ./release.sh

    - name: upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-beta"
        prerelease: true
        title: "Beta build"
        files: |
         
          g2fm-en_US.7z
          g2fm_multiarch.iso
          g2fmia32.efi
          g2fmx64.efi
          g2fm_multiarch.iso
          grubfm.elf
          grubfm.iso
          grubfmaa64.efi
          grubfm_pc.iso
