name: Build G2FM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Build
      run: |
        ./release.sh

    - name: Upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v1.0.0-beta"
        prerelease: false
        title: "Beta build"
        files: |
          g2fm-en_US.7z
          g2fmia32.efi
          g2fmx64.efi
          grubfm.elf
          grubfm.iso
          grubfmaa64.efi
          samples.7z
