name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: initialize
      run: |
        sudo -E apt-get -y install gettext grub2-common genisoimage p7zip-full mtools xorriso

    - name: update grub2
      run: ./update_grub2.sh

    - name: build
      run: |
        ./release.sh
        echo "3" | ./build.sh

    - name: upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Beta build"
        files: |
         
          grubfm-en_US.7z
          grubfm_multiarch.iso
