name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! Thank you for your first issue! **Please make sure your issue is labeled correctly.** Just a notice. Also since the owner of this repo has a lot of free time, he should respond shortly."
        pr-message: "Hi there, thanks for your first contribution! The owner should respond *at least* in a hour. The max is a day."
